services:
  client:
    container_name: client
    image: client-prod
    build:
      dockerfile: ./client/Dockerfile
      target: production
    ports:
      - "80:8002"
    depends_on:
      - server
      - mongo
    links:
      - server
      - mongo
  server:
    container_name: server
    image: server-prod
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5002"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    container_name: MONGODB
    ports:
      - "27017"
